# .github/workflows/deploy.yml
name: Deploy to Live

on:
  push:
    branches:
      - main

jobs:
  deploy_live:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ELORA_EX }}"
          projectId: elora-ex
          channelId: live
