# .github/workflows/preview.yml
name: Preview Deployment

on:
  pull_request:
permissions:
  contents: read
  checks: write
jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build


      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ELORA_EX }}"
          projectId: elora-ex
          expires: 30d
